name: Build and Publish Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-publish:
    uses: halkeye/halkeye/.github/workflows/build-upstream-docker.yaml@master
    secrets: inherit
    permissions:
      contents: write
      packages: write
    with:
      upstream_version: "add-env-for-mastodon"
      upstream_repo: "https://github.com/gitroomhq/postiz-app"
      checkout_upstream_repo: "halkeye/postiz-app"
      dockerfile: "Dockerfile.dev"
      run_number: "${{ github.run_number }}"
      username: "${{ github.repository_owner }}"
      repository: "${{ github.repository }}"
      platforms: linux/amd64
